export enum WeddingEventContext {
  PRE_WEDDING = "PRE_WEDDING",
  HALDI = "HALDI",
  MEHNDI = "MEHNDI",
  SANGEET = "SANGEET",
  BARAAT = "BARAAT",
  WEDDING = "WEDDING",
  RECEPTION = "RECEPTION",
  BABY_SHOWER = "BABY_SHOWER",
  ENGAGEMENT = "ENGAGEMENT"
}
