import { AutoEditMode } from '../types';

export const AUTO_EDIT_MODES: AutoEditMode[] = [
  'Auto Reel',
  'Auto Highlight Film',
  'Auto Teaser',
  'Baby Shower Reel',
  'Engagement Reel',
  'Save The Date',
  'Pre-Wedding Film',
  'Haldi Highlight',
  'Mehndi Highlight',
  'Sangeet Highlight',
  'Baraat Highlight',
  'Wedding Ceremony',
  'Reception Highlight',
  'Couple Story',
  'Family Story',
  'Instagram Reel',
  'YouTube Highlight',
  'Vertical Shorts',
  'Cinematic Film',
];

export const AUTO_EDIT_MODE_LABELS: Record<AutoEditMode, string> = {
  'Auto Reel': 'Full-length ceremony reel optimized for storytelling',
  'Auto Highlight Film': 'Highlight film with emotional beats and story arcs',
  'Auto Teaser': 'Short cinematic teaser for social media',
  'Baby Shower Reel': 'Sacred and intimate baby shower reel',
  'Engagement Reel': 'Romantic engagement sequence with emotional pacing',
  'Save The Date': 'Playful announcement teaser with stylish edits',
  'Pre-Wedding Film': 'Pre-wedding story film with romantic tone',
  'Haldi Highlight': 'Bright Haldi highlight edit with color pops',
  'Mehndi Highlight': 'Rich Mehndi highlight edit with detail shots',
  'Sangeet Highlight': 'Energetic Sangeet reel with dance dynamics',
  'Baraat Highlight': 'Powerful Baraat highlight with procession energy',
  'Wedding Ceremony': 'Ceremony edit with sacred ritual focus',
  'Reception Highlight': 'Reception highlight with celebration and glamour',
  'Couple Story': 'Couple story edit with emotional voiceover flow',
  'Family Story': 'Family-centered edit with cherished moments',
  'Instagram Reel': 'Vertical short cut for Instagram engagement',
  'YouTube Highlight': 'YouTube-ready highlight with clean pacing',
  'Vertical Shorts': 'Mobile-first vertical short with punchy edits',
  'Cinematic Film': 'Premium cinematic wedding film with mood and luxury',
};
