from __future__ import annotations
from pydantic import BaseModel, Field
from typing import List, Literal, Optional, Tuple, Union

from .models import SidecarStatus
from .face_models import FaceReport

EMOTION_MODEL_VERSION = "phase-8-emotion-v1"

ExpressionLabel = Literal[
    "smiling",
    "neutral",
    "surprised",
    "sad-looking",
    "tense",
    "laughing",
    "eyes-closed",
    "uncertain"
]

ClipMoodLabel = Literal[
    "joyful",
    "romantic",
    "emotional",
    "energetic",
    "calm",
    "celebratory",
    "humorous",
    "tense",
    "neutral",
    "uncertain"
]

EditorialRecommendation = Literal[
    "longer-hold",
    "normal",
    "fast-reaction",
    "avoid",
    "uncertain"
]

class ExpressionProviderStatus(BaseModel):
    """Describes the status of a specific expression provider."""
    name: str
    enabled: bool
    reason: Optional[str] = None

class EmotionCapabilities(BaseModel):
    """Describes the capabilities of the emotion analysis service."""
    available: bool
    version: str = EMOTION_MODEL_VERSION
    providers: List[ExpressionProviderStatus] = []
    reason: Optional[str] = None

class EmotionEvidence(BaseModel):
    """Evidence for a particular emotional estimate."""
    source: Literal["expression", "motion", "vision", "wedding", "temporal"]
    description: str
    value: Union[float, str]
    weight: float

class FacialExpressionEstimate(BaseModel):
    """An estimate of a facial expression for a single face in a frame."""
    faceId: str
    label: ExpressionLabel
    confidence: float = Field(..., ge=0, le=1)
    evidence: List[EmotionEvidence] = []
    provider: str
    quality_warning: Optional[str] = None
    uncertainty_reason: Optional[str] = None

class FaceExpressionFrame(BaseModel):
    """Contains all expression estimates for a single frame."""
    frameSampleId: str
    timestamp: float
    expressions: List[FacialExpressionEstimate] = []

class EmotionTimelineEntry(BaseModel):
    """An entry in the timeline of emotional analysis."""
    time: float
    label: str
    value: Union[float, str]

class ClipExpressionSummary(BaseModel):
    """Summary of expressions found within a single clip."""
    dominant_expression: Optional[ExpressionLabel] = None
    dominant_confidence: float = 0
    secondary_expression: Optional[ExpressionLabel] = None
    smile_score: float = Field(default=0, ge=0, le=100)
    expression_score: float = Field(default=0, ge=0, le=100)
    expression_stability: float = Field(default=0, ge=0, le=1)
    timeline: List[EmotionTimelineEntry] = []

class ClipMoodEstimate(BaseModel):
    """An overall emotional mood estimate for an entire clip."""
    dominant_mood: ClipMoodLabel
    secondary_mood: Optional[ClipMoodLabel] = None
    confidence: float = Field(..., ge=0, le=1)
    evidence: List[EmotionEvidence] = []
    usable_for_edit: bool
    recommended_handling: EditorialRecommendation
    uncertainty_reason: Optional[str] = None

class EmotionClipReport(BaseModel):
    """Full emotion analysis report for a single clip."""
    clipId: str
    expression_summary: ClipExpressionSummary
    mood_estimate: ClipMoodEstimate

class EmotionReport(BaseModel):
    """The final report generated by an emotion analysis job."""
    jobId: str
    requestId: str
    status: Literal["running", "completed", "cancelled", "failed", "sidecar-unavailable"]
    sidecar: SidecarStatus
    emotionModelVersion: str = EMOTION_MODEL_VERSION
    capabilities: EmotionCapabilities
    progress: dict
    clips: List[EmotionClipReport] = []
    failures: List[dict] = []
    warnings: List[str] = []
    startedAt: str
    completedAt: Optional[str] = None

class EmotionRequest(BaseModel):
    """Request to start an emotion analysis job."""
    schemaVersion: Literal[1]
    jobId: str
    requestId: str
    requestedAt: str
    approvedRoots: List[str]
    faceReport: FaceReport # Depends on the result of the Face Analysis phase
    cache: dict
    limits: dict
